server:
  port: 9292
  servlet:
    context-path: '/speak-app'

spring:
  main:
    banner-mode: 'off'
  application:
    name: 'speak-backend'
  profiles:
    active: 'dev'
  datasource:
    url: jdbc:postgresql://localhost:5432/speak_db?useSSL=false&useFractionalSeconds=true
    username: UserPg.
    password: PgSpeakApp.
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update #en prod validate
    show-sql: true #en prod false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        cache:
          use_query_cache: false
          use_second_level_cache: false

speak-backend:
  client:
    openai:
      api-key: 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
      gpt-model: gpt-3.5-turbo
      audio-model: whisper-1
      http-client:
        read-timeout-ms: 3000
        connect-timeout-ms: 3000
      urls:
        base-url: https://api.openai.com/v1
        chat-url: /chat/completions
        create-transcription-url: /audio/transcriptions

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: beta
  datasource:
    url: jdbc:postgresql://postgres_speak:5432/speak_db?useSSL=false&useFractionalSeconds=true
---