server:
  port: 9292
  servlet:
    context-path: '/speak-app'

spring:
  servlet:
    multipart:
      enabled: true # Enable multipart uploads
      file-size-threshold: 2KB # Threshold after which files are written to disk.
      max-file-size: 20MB # Max file size.
      max-request-size: 20MB  # Max Request Size
  application:
    name: 'speak-backend'
  profiles:
    active: 'dev'
  datasource:
    url: jdbc:postgresql://localhost:5432/speak_db?useSSL=false&useFractionalSeconds=true
    username: UserPg.
    password: PgSpeakApp.
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none #en prod validate
    show-sql: true #en prod false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        cache:
          use_query_cache: false
          use_second_level_cache: false

speak-backend:
  count-exercise: 5
  jwt:
    secret-key: secret #$2a$10$x7pFiWQLFVfoBdMmUX4fBedY
    expiration-token: 7d
    refresh-expiration-token: 7d
  client:
    whisper:
      url: ${URL_WHISPER_API}
      #url: https://api.openai.com/v1/audio/transcriptions
      api-key: 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
      connect-timeout: 100s
      read-timeout: 100s
      headers:
        Content-Type: multipart/form-data
        X-Client: ${spring.profiles.active}-${spring.application.name}

---
spring:
  config:
    activate:
      on-profile: dev

speak-backend:
  client:
    whisper:
      url: https://32c5-104-198-107-50.ngrok-free.app/transcription-audio

---
spring:
  config:
    activate:
      on-profile: beta
  datasource:
    url: jdbc:postgresql://postgres_speak:5432/speak_db?useSSL=false&useFractionalSeconds=true
---