server:
  port: 9292
  servlet:
    context-path: '/speak-app'

spring:
  servlet:
    multipart:
      enabled: true # Enable multipart uploads
      file-size-threshold: 2KB # Threshold after which files are written to disk.
      max-file-size: 20MB # Max file size.
      max-request-size: 20MB  # Max Request Size
  main:
    banner-mode: 'off'
  application:
    name: 'speak-backend'
  profiles:
    active: 'dev'
  datasource:
    url: jdbc:postgresql://localhost:5432/speak_db?useSSL=false&useFractionalSeconds=true
    username: UserPg.
    password: PgSpeakApp.
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #en prod validate
    show-sql: true #en prod false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        cache:
          use_query_cache: false
          use_second_level_cache: false

speak-backend:
  client:
    whisper:
      url: https://api.openai.com/v1/audio/transcriptions
      api-key: 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
      connect-timeout: 100s
      read-timeout: 100s
      headers:
        Content-Type: multipart/form-data
        X-Client: ${spring.profiles.active}-${spring.application.name}

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: beta
  datasource:
    url: jdbc:postgresql://postgres_speak:5432/speak_db?useSSL=false&useFractionalSeconds=true
---