version: "3.6"

services:
  
  postgres_speak:
    image: postgres:15
    container_name: postgres_speak
    hostname: postgres_speak
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: PgSpeakApp.
      POSTGRES_USER: UserPg.
      POSTGRES_DB: speak_db
      PGDATA: /var/lib/postgresql/data/pg_data
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
      - './db-scripts/:/docker-entrypoint-initdb.d/'
    networks:
      - network_speak
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  speak_app:
    image: speak_app
    container_name: speak_app
    hostname: speak_app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      URL_WHISPER_API: "https://0216-34-41-214-222.ngrok-free.app/transcription-audio"
    ports:
      - "9292:9292"
    volumes:
      - "speak_app_data:/root/"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    depends_on:
      - postgres_speak
    networks:
      - network_speak


networks:
  network_speak:
    name: network_speak

volumes:
  postgres_data:
    driver: local
  speak_app_data:
    driver: local