version: "3.6"

services:
  
  postgres:
    image: postgres:13.4
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: PasswordO1.
      POSTGRES_USER: sa
      POSTGRES_DB_CUSTOM: speak_db
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
      - './db-scripts/:/docker-entrypoint-initdb.d/'
    networks:
      - network_speak
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  speak_app:
    image: speak_app
    container_name: speak_app
    hostname: speak_app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "9292:9292"
    volumes:
      - "speak_app_data:/opt/"
    networks:
      - network_speak


networks:
  network_speak:
    name: network_speak

volumes:
  postgres_data:
    driver: local
  speak_app_data:
    driver: local