ALTER TABLE tm_task_group
ALTER COLUMN start_date TYPE TIMESTAMP;

ALTER TABLE tm_task_group
ALTER COLUMN end_date TYPE TIMESTAMP;

ALTER TABLE tm_task_group_detail ALTER COLUMN url_audio TYPE varchar(255);
ALTER TABLE tm_task_group_detail ALTER COLUMN result TYPE varchar(255);

ALTER TABLE tm_task_group_detail ALTER COLUMN url_audio DROP NOT NULL;
ALTER TABLE tm_task_group_detail ALTER COLUMN result DROP NOT NULL;
/*TODO
ALTER TABLE tm_task_group_detail RENAME TO tm_task_item;
ALTER TABLE tm_task_group RENAME TO tm_task;

ALTER TABLE tm_task RENAME COLUMN id_task_group TO id_task;
ALTER TABLE tm_task_item RENAME COLUMN id_task TO id_task_item;
ALTER TABLE tm_task_item RENAME COLUMN id_task_group TO id_task;
*/

CREATE TABLE IF NOT EXISTS public.tm_task_item_detail
(
    id_task_item_detail         BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_task_item                BIGINT NOT NULL,
    id_image_selected           BIGINT NOT NULL,
    result_selected             varchar(255),
    PRIMARY KEY (id_task_item_detail),
    FOREIGN KEY (id_task_item) REFERENCES tm_task_group_detail (id_task),
    FOREIGN KEY (id_image_selected) REFERENCES tm_image (id_image)
);