CREATE TABLE IF NOT EXISTS public.tm_chat
(
    id_chat                     BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_patient                  BIGINT NOT NULL,
    id_professional             BIGINT NOT NULL,
    PRIMARY KEY (id_chat),
    UNIQUE (id_patient, id_professional),
    FOREIGN KEY (id_patient) REFERENCES tm_patient (id_patient),
    FOREIGN KEY (id_professional) REFERENCES tm_professional (id_professional)
);

CREATE TABLE IF NOT EXISTS public.tm_chat_message
(
    id_message                  BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_chat                     BIGINT NOT NULL,
    status                      varchar(10) NOT NULL,
    message                     varchar NOT NULL,
    type                        varchar(10) NOT NULL,
    created_at                  TIMESTAMP NOT NULL,
    is_author_patient           BOOLEAN NOT NULL,
    PRIMARY KEY (id_message),
    FOREIGN KEY (id_chat) REFERENCES tm_chat (id_chat)
);