CREATE TABLE IF NOT EXISTS public.tm_report
(
    id_report                   BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_patient                  BIGINT NOT NULL,
    id_professional             BIGINT NOT NULL,
    created_at                  TIMESTAMP NOT NULL,
    title                       varchar NOT NULL,
    body                        varchar NOT NULL,
    PRIMARY KEY (id_report),
    FOREIGN KEY (id_patient) REFERENCES tm_patient (id_patient),
    FOREIGN KEY (id_professional) REFERENCES tm_professional (id_professional)
);