INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1751, 19, 'Marina come una naranja', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1752, 19, 'Mariano usa el paraguas', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1753, 19, 'Carola usa una pollera', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1754, 19, 'Ariel come una pera', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1755, 19, 'Ariana tiene muchas biromes', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1756, 19, 'Mariana vio una jirafa', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1757, 19, 'Carola come duraznos', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1758, 19, 'María vio una mariposa', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1759, 19, 'Mario tiene un loro', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1760, 19, 'Ariana tiene caramelos', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1761, 20, 'El perro está en el parque', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1762, 20, 'Ramiro tiene una remera roja', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1763, 20, 'Rosa tiene un perro', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1764, 20, 'La rana está en el jardín', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1765, 20, 'Hay muchos árboles en el parque', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1766, 20, 'Rocío tiene un reloj rosa', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1767, 20, 'El árbol tiene una rama rota', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1768, 20, 'Rita pinta la reja con rodillo', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1769, 20, 'Hay orcas en el mar', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1770, 20, 'La reina está en la torre', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1771, 21, 'Bruno lee muchos libros', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1772, 21, 'Brenda tiene un abrigo', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1773, 21, 'Gabriela se olvidó su abrigo y su sombrero', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1774, 21, 'Bruno se quebró el brazo', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1775, 21, 'Gabriel lee libros y hace bromas', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1776, 21, 'Las croquetas tienen crema', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1777, 21, 'El secretario tiene un micrófono', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1778, 21, 'Cristina cruzó y tomó el micro', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1779, 21, 'Cristian come croquetas con crema', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1780, 21, 'La copa de cristal está en el escritorio', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1781, 21, 'Andrea pintó un cuadro', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1782, 21, 'Sandra dibujó un dragón', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1783, 21, 'Andrés y Sandra comen almendras', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1784, 21, 'El padre de Andrea colgó el cuadro', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1785, 21, 'Adrián y Pedro vieron golondrinas', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1786, 21, 'Andrea siempre pide helado de almendra', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1787, 21, 'Franco come una frutilla', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1788, 21, 'Francisco siente frío', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1789, 21, 'Franco tiene un frasco de frutillas', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1790, 21, 'Las fresas y frambuesas son frutas', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1791, 21, 'Fredi se puso la frazada porque tenía frío', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1792, 21, 'El frasco está lleno de fresas', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1793, 21, 'En el tren tocan la trompeta', 3, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1794, 21, 'Trinidad juega con trompos y trenes', 3, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1795, 21, 'El tren atravesó tres puentes', 3, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1796, 21, 'El otro día gane un trofeo', 3, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1797, 21, 'Mi primo ganó un premio', 3, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1798, 21, 'Mi prima ama la primavera', 3, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1799, 21, 'Mi prima y mi primo ganaron un premio', 3, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1800, 21, 'El profesor siempre llega temprano', 3, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1801, 21, 'El grillo encontró un cangrejo', 3, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1802, 21, 'En la granja hay un grupo de grillos', 3, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1803, 21, 'Greta es muy graciosa y come grisines', 3, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1804, 11, 'El abuelo lee un libro', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1805, 11, 'Lila usa sandalias ', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1806, 11, 'Lalo usa la mochila', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1807, 11, 'Lucho juega con la pelota', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1808, 11, 'Lalo lee un lindo en la sala', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1809, 11, 'Mariela come solo limones y melones', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1810, 11, 'La pelota de Lucho está en el salón', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1811, 11, 'Lila lava la lechuga en la pileta', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1812, 11, 'El lápiz de Luis es liso y azul', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1813, 11, 'Lalo vive en una isla', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1814, 12, 'Ella llegó a su casa', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1815, 12, 'Llovió todo el día de ayer', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1816, 12, 'La llama que llama', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1817, 12, 'La toalla es amarilla', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1818, 12, 'Ella tiene un anillo', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1819, 12, 'Hay muchos grillos en la calle', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1820, 12, 'El cielo esta lleno de estrellas', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1821, 12, 'Ellos tienen zapatillas amarillas', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1822, 12, 'Ella tiene un cepillo amarillo', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1823, 12, 'Ella tiene un pollito y un caballo', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1824, 13, 'Pablo pinta la tabla', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1825, 13, 'El cable es blanco', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1826, 13, 'Pablo tiene una blusa blanca', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1827, 13, 'El cable es muy blando y está doblado', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1828, 13, 'El mueble tiene tablas y bloques', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1829, 13, 'Clara come chicle', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1830, 13, 'Claudio usa el teclado', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1831, 13, 'Claudia fue a la clase de clarinete', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1832, 13, 'Clara va al club en bicicleta', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1833, 13, 'Clemente come chicles y pochoclos', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1834, 13, 'Florencia toca la flauta', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1835, 13, 'Flavio come un flan', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1836, 13, 'Florencia es flaca y come flan', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1837, 13, 'Flor usa flequillo y toca la flauta', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1838, 13, 'Gladis tiene un globo', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1839, 13, 'Gloria dibuja un iglú', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1840, 13, 'Gladis dibuja gladiolos y globos', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1841, 13, 'Gloria habla inglés y es muy glotona', 2, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1842, 13, 'El plumero tiene plumas', 3, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1843, 13, 'En la plaza hay plantas', 3, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1844, 13, 'La plancha está en el placar', 3, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1845, 13, 'En la playa festejan un cumple', 3, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1846, 13, 'En el cumple jugaron con plumas y plastilinas', 3, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1847, 5, 'Diana come budines', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1848, 5, 'Diego juega  con los dados', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1849, 5, 'Denise usa medias', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1850, 5, 'Dante come sandía', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1851, 5, 'Diana usa un divino vestido de seda', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1852, 5, 'Daniel come dulce de damasco', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1853, 5, 'Dina usa medias con distintos dibujos', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1854, 5, 'Dante hace asados todos los domingos', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1855, 5, 'Las monedas de Dalia están escondidas', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1856, 5, 'Diego juega con los dados y el dominó', 1, 'phrase', 'speak', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1857, 19, 'Marina come una naranja', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1858, 19, 'Mariano usa el paraguas', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1859, 19, 'Carola usa una pollera', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1860, 19, 'Ariel come una pera', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1861, 19, 'Ariana tiene muchas biromes', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1862, 19, 'Mariana vio una jirafa', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1863, 19, 'Carola come duraznos', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1864, 19, 'María vio una mariposa', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1865, 19, 'Mario tiene un loro', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1866, 19, 'Ariana tiene caramelos', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1867, 20, 'El perro está en el parque', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1868, 20, 'Ramiro tiene una remera roja', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1869, 20, 'Rosa tiene un perro', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1870, 20, 'La rana está en el jardín', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1871, 20, 'Hay muchos árboles en el parque', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1872, 20, 'Rocío tiene un reloj rosa', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1873, 20, 'El árbol tiene una rama rota', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1874, 20, 'Rita pinta la reja con rodillo', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1875, 20, 'Hay orcas en el mar', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1876, 20, 'La reina está en la torre', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1877, 21, 'Bruno lee muchos libros', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1878, 21, 'Brenda tiene un abrigo', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1879, 21, 'Gabriela se olvidó su abrigo y su sombrero', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1880, 21, 'Bruno se quebró el brazo', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1881, 21, 'Gabriel lee libros y hace bromas', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1882, 21, 'Las croquetas tienen crema', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1883, 21, 'El secretario tiene un micrófono', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1884, 21, 'Cristina cruzó y tomó el micro', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1885, 21, 'Cristian come croquetas con crema', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1886, 21, 'La copa de cristal está en el escritorio', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1887, 21, 'Andrea pintó un cuadro', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1888, 21, 'Sandra dibujó un dragón', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1889, 21, 'Andrés y Sandra comen almendras', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1890, 21, 'El padre de Andrea colgó el cuadro', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1891, 21, 'Adrián y Pedro vieron golondrinas', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1892, 21, 'Andrea siempre pide helado de almendra', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1893, 21, 'Franco come una frutilla', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1894, 21, 'Francisco siente frío', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1895, 21, 'Franco tiene un frasco de frutillas', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1896, 21, 'Las fresas y frambuesas son frutas', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1897, 21, 'Fredi se puso la frazada porque tenía frío', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1898, 21, 'El frasco está lleno de fresas', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1899, 21, 'En el tren tocan la trompeta', 3, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1900, 21, 'Trinidad juega con trompos y trenes', 3, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1901, 21, 'El tren atravesó tres puentes', 3, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1902, 21, 'El otro día gane un trofeo', 3, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1903, 21, 'Mi primo ganó un premio', 3, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1904, 21, 'Mi prima ama la primavera', 3, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1905, 21, 'Mi prima y mi primo ganaron un premio', 3, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1906, 21, 'El profesor siempre llega temprano', 3, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1907, 21, 'El grillo encontró un cangrejo', 3, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1908, 21, 'En la granja hay un grupo de grillos', 3, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1909, 21, 'Greta es muy graciosa y come grisines', 3, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1910, 11, 'El abuelo lee un libro', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1911, 11, 'Lila usa sandalias ', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1912, 11, 'Lalo usa la mochila', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1913, 11, 'Lucho juega con la pelota', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1914, 11, 'Lalo lee un lindo en la sala', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1915, 11, 'Mariela come solo limones y melones', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1916, 11, 'La pelota de Lucho está en el salón', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1917, 11, 'Lila lava la lechuga en la pileta', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1918, 11, 'El lápiz de Luis es liso y azul', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1919, 11, 'Lalo vive en una isla', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1920, 12, 'Ella llegó a su casa', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1921, 12, 'Llovió todo el día de ayer', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1922, 12, 'La llama que llama', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1923, 12, 'La toalla es amarilla', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1924, 12, 'Ella tiene un anillo', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1925, 12, 'Hay muchos grillos en la calle', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1926, 12, 'El cielo esta lleno de estrellas', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1927, 12, 'Ellos tienen zapatillas amarillas', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1928, 12, 'Ella tiene un cepillo amarillo', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1929, 12, 'Ella tiene un pollito y un caballo', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1930, 13, 'Pablo pinta la tabla', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1931, 13, 'El cable es blanco', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1932, 13, 'Pablo tiene una blusa blanca', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1933, 13, 'El cable es muy blando y está doblado', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1934, 13, 'El mueble tiene tablas y bloques', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1935, 13, 'Clara come chicle', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1936, 13, 'Claudio usa el teclado', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1937, 13, 'Claudia fue a la clase de clarinete', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1938, 13, 'Clara va al club en bicicleta', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1939, 13, 'Clemente come chicles y pochoclos', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1940, 13, 'Florencia toca la flauta', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1941, 13, 'Flavio come un flan', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1942, 13, 'Florencia es flaca y come flan', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1943, 13, 'Flor usa flequillo y toca la flauta', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1944, 13, 'Gladis tiene un globo', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1945, 13, 'Gloria dibuja un iglú', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1946, 13, 'Gladis dibuja gladiolos y globos', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1947, 13, 'Gloria habla inglés y es muy glotona', 2, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1948, 13, 'El plumero tiene plumas', 3, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1949, 13, 'En la plaza hay plantas', 3, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1950, 13, 'La plancha está en el placar', 3, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1951, 13, 'En la playa festejan un cumple', 3, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1952, 13, 'En el cumple jugaron con plumas y plastilinas', 3, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1953, 5, 'Diana come budines', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1954, 5, 'Diego juega  con los dados', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1955, 5, 'Denise usa medias', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1956, 5, 'Dante come sandía', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1957, 5, 'Diana usa un divino vestido de seda', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1958, 5, 'Daniel come dulce de damasco', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1959, 5, 'Dina usa medias con distintos dibujos', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1960, 5, 'Dante hace asados todos los domingos', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1961, 5, 'Las monedas de Dalia están escondidas', 1, 'phrase', 'order_word', 'NULL');
INSERT INTO public.tm_exercise (id_exercise, id_phoneme, result_expected, level, category, type, incorrect) VALUES (1962, 5, 'Diego juega con los dados y el dominó', 1, 'phrase', 'order_word', 'NULL');